/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Enki
 */
public class Stats extends javax.swing.JFrame {
    /**
     * Creates new form Stats
     */
    public Stats() {
        initComponents();
         Name1.setText("Fulano");
         MAXHP1.setText("250");
         ATK1.setText(""+(int) Math.floor(Math.random()*10));
         DEF1.setText(""+(int) Math.floor(Math.random()*10));
         CRIT1.setText(""+(int) Math.floor(Math.random()*100));
         Name2.setText("Pepito");
         MAXHP2.setText("250");
         ATK2.setText(""+(int) Math.floor(Math.random()*10));
         DEF2.setText(""+(int) Math.floor(Math.random()*10));
         CRIT2.setText(""+(int) Math.floor(Math.random()*100));
         
    }
    
    public String getName1(){
        return Name1.getText();
    }
    
    public Stats (int gg) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name1 = new javax.swing.JTextField();
        MAXHP1 = new javax.swing.JTextField();
        ATK1 = new javax.swing.JTextField();
        DEF1 = new javax.swing.JTextField();
        CRIT1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ATK2 = new javax.swing.JTextField();
        CRIT2 = new javax.swing.JTextField();
        DEF2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Name2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        MAXHP2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(312, 220));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 60, 22));
        getContentPane().add(MAXHP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 65, 60, 22));
        getContentPane().add(ATK1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 60, 22));
        getContentPane().add(DEF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 115, 60, 22));
        getContentPane().add(CRIT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 60, 22));

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 44, -1, -1));

        jLabel2.setText("Personagem 1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 14, -1, -1));

        jLabel3.setText("MAXHP:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 69, -1, -1));

        jLabel4.setText("ATK:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, -1, -1));

        jLabel5.setText("DEF:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 119, -1, -1));

        jLabel6.setText("CRIT:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 144, -1, -1));
        getContentPane().add(ATK2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 60, 22));
        getContentPane().add(CRIT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 60, 22));
        getContentPane().add(DEF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 115, 60, 22));

        jLabel7.setText("Nome:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 44, -1, -1));

        jLabel8.setText("Personagem 2");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 14, -1, -1));

        jLabel9.setText("MAXHP:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 69, -1, -1));

        jLabel10.setText("ATK:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 94, -1, -1));
        getContentPane().add(Name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 60, 22));

        jLabel11.setText("DEF:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 119, -1, -1));
        getContentPane().add(MAXHP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 65, 60, 22));

        jLabel12.setText("CRIT:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 144, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              new Stats().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ATK1;
    private javax.swing.JTextField ATK2;
    private javax.swing.JTextField CRIT1;
    private javax.swing.JTextField CRIT2;
    private javax.swing.JTextField DEF1;
    private javax.swing.JTextField DEF2;
    private javax.swing.JTextField MAXHP1;
    private javax.swing.JTextField MAXHP2;
    private javax.swing.JTextField Name1;
    private javax.swing.JTextField Name2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
